import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
/**
 *
 * @author cScientist
 */
public class AdminJFrame extends javax.swing.JFrame {

    UrunGoster urunjframe=new UrunGoster();
    String tuzMiktarı="";
    double buzMiktarı;
    public AdminJFrame() {
        initComponents();
        setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
        setPanels();
        
        
    }
    public void setPanels(){
        PinnerTatlı.setVisible(false);
        pinnerİcecek.setVisible(false);
        pinnerYemek.setVisible(false);
        Piçecek.setVisible(false);
        Ptatlı.setVisible(false);
        Pyemek.setVisible(false);
        
    }
    
    
    
    public void clear(){
        
        tfyfiyat.setText("");
        tftfiyat.setText("");
        tfifiyat.setText("");
        tfyisim.setText("");
        tftisim.setText("");
        tfiisim.setText("");
        jcbTatlı.setSelectedIndex(-1);
        jcbYemek.setSelectedIndex(-1);
        jcbİçecek.setSelectedIndex(-1);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        bgyemek = new javax.swing.ButtonGroup();
        bgicecek = new javax.swing.ButtonGroup();
        jCheckBox4 = new javax.swing.JCheckBox();
        bgtatlı = new javax.swing.ButtonGroup();
        bgazcokorta = new javax.swing.ButtonGroup();
        mainpanel = new javax.swing.JPanel(){

            public void paintComponent(Graphics g){
                ImageIcon ım=new ImageIcon("NABER.jpg");
                Image i=ım.getImage();

                g.drawImage(i, 5, 0, this.getSize().width,this.getSize().height, this);

            }

        };
        JRyemek = new javax.swing.JRadioButton();
        JRiçecek = new javax.swing.JRadioButton();
        JRtatlı = new javax.swing.JRadioButton();
        Piçecek = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfiisim = new javax.swing.JTextField();
        tfifiyat = new javax.swing.JTextField();
        jcbİçecek = new javax.swing.JComboBox<>();
        psıc = new javax.swing.JPanel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        psoguk = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        cbaz = new javax.swing.JCheckBox();
        cbOrta = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        Pyemek = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfyisim = new javax.swing.JTextField();
        tfyfiyat = new javax.swing.JTextField();
        jcbYemek = new javax.swing.JComboBox<>();
        pAna = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        pAtıs = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        tfcalori = new javax.swing.JTextField();
        Ptatlı = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tftisim = new javax.swing.JTextField();
        tftfiyat = new javax.swing.JTextField();
        jcbTatlı = new javax.swing.JComboBox<>();
        psütlü = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        tfWithWhat = new javax.swing.JTextField();
        pSerbetli = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        tfSugar = new javax.swing.JTextField();
        bEkle = new javax.swing.JButton();
        bSil = new javax.swing.JButton();
        bUrunleriGoster = new javax.swing.JButton();
        pinnerYemek = new javax.swing.JPanel();
        cbAnaYemek = new javax.swing.JCheckBox();
        cbAtıstırmalıkl = new javax.swing.JCheckBox();
        pinnerİcecek = new javax.swing.JPanel();
        cbSıcak = new javax.swing.JCheckBox();
        cbSoguk = new javax.swing.JCheckBox();
        PinnerTatlı = new javax.swing.JPanel();
        cbSutlu = new javax.swing.JCheckBox();
        cbSerbetli = new javax.swing.JCheckBox();

        jCheckBox4.setText("jCheckBox4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JRyemek.setBackground(new java.awt.Color(240, 197, 73));
        buttonGroup1.add(JRyemek);
        JRyemek.setText("YEMEK");
        JRyemek.setOpaque(false);
        JRyemek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRyemekActionPerformed(evt);
            }
        });

        JRiçecek.setBackground(new java.awt.Color(240, 197, 73));
        buttonGroup1.add(JRiçecek);
        JRiçecek.setText("İÇECEK");
        JRiçecek.setOpaque(false);
        JRiçecek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRiçecekActionPerformed(evt);
            }
        });

        JRtatlı.setBackground(new java.awt.Color(240, 197, 73));
        buttonGroup1.add(JRtatlı);
        JRtatlı.setText("TATLI");
        JRtatlı.setOpaque(false);
        JRtatlı.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRtatlıActionPerformed(evt);
            }
        });

        Piçecek.setBorder(javax.swing.BorderFactory.createTitledBorder("İÇECEK"));
        Piçecek.setOpaque(false);

        jLabel1.setText("İSİM");

        jLabel3.setText("FİYAT");

        jLabel4.setText("TÜR");

        jcbİçecek.setBackground(new java.awt.Color(240, 197, 73));
        jcbİçecek.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Asitli ", "Asitsiz " }));
        jcbİçecek.setSelectedIndex(-1);

        psıc.setOpaque(false);
        psıc.setPreferredSize(new java.awt.Dimension(206, 69));

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(50, null, 100, 10));
        jSpinner1.setOpaque(false);

        jLabel15.setText("°C");

        jLabel16.setText("Sıcaklığı");

        javax.swing.GroupLayout psıcLayout = new javax.swing.GroupLayout(psıc);
        psıc.setLayout(psıcLayout);
        psıcLayout.setHorizontalGroup(
            psıcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(psıcLayout.createSequentialGroup()
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addGap(20, 20, 20))
        );
        psıcLayout.setVerticalGroup(
            psıcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, psıcLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(psıcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addContainerGap())
        );

        psoguk.setOpaque(false);

        jLabel17.setText("Buz Miktarı");

        jProgressBar1.setBackground(new java.awt.Color(255, 255, 255));
        jProgressBar1.setForeground(new java.awt.Color(240, 197, 73));

        bgazcokorta.add(cbaz);
        cbaz.setText("Az");
        cbaz.setOpaque(false);
        cbaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbazActionPerformed(evt);
            }
        });

        bgazcokorta.add(cbOrta);
        cbOrta.setText("Orta");
        cbOrta.setOpaque(false);
        cbOrta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbOrtaActionPerformed(evt);
            }
        });

        bgazcokorta.add(jCheckBox6);
        jCheckBox6.setText("Cok");
        jCheckBox6.setOpaque(false);
        jCheckBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout psogukLayout = new javax.swing.GroupLayout(psoguk);
        psoguk.setLayout(psogukLayout);
        psogukLayout.setHorizontalGroup(
            psogukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(psogukLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(psogukLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cbaz)
                .addGap(18, 18, 18)
                .addComponent(cbOrta)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox6))
        );
        psogukLayout.setVerticalGroup(
            psogukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(psogukLayout.createSequentialGroup()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(psogukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbaz)
                    .addComponent(cbOrta)
                    .addComponent(jCheckBox6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PiçecekLayout = new javax.swing.GroupLayout(Piçecek);
        Piçecek.setLayout(PiçecekLayout);
        PiçecekLayout.setHorizontalGroup(
            PiçecekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PiçecekLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PiçecekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PiçecekLayout.createSequentialGroup()
                        .addGroup(PiçecekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(psıc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(PiçecekLayout.createSequentialGroup()
                                .addGroup(PiçecekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(PiçecekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfiisim)
                                    .addComponent(tfifiyat)
                                    .addComponent(jcbİçecek, 0, 101, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(psoguk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        PiçecekLayout.setVerticalGroup(
            PiçecekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PiçecekLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PiçecekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfiisim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(PiçecekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfifiyat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(28, 28, 28)
                .addGroup(PiçecekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jcbİçecek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(psıc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(psoguk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Pyemek.setBorder(javax.swing.BorderFactory.createTitledBorder("YEMEK"));
        Pyemek.setOpaque(false);

        jLabel5.setText("İSİM");

        jLabel7.setText("FİYAT");

        jLabel8.setText("SÜRE");

        jcbYemek.setBackground(new java.awt.Color(240, 197, 73));
        jcbYemek.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5-10dk", "10-20dk", "20 30dk" }));
        jcbYemek.setSelectedIndex(-1);

        pAna.setOpaque(false);

        jLabel2.setText("Pişirme Oranı");

        jSlider1.setMaximum(3);
        jSlider1.setMinimum(1);
        jSlider1.setOpaque(false);
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });

        jLabel10.setText("0");

        jLabel13.setText("50");

        jLabel14.setText("100");

        javax.swing.GroupLayout pAnaLayout = new javax.swing.GroupLayout(pAna);
        pAna.setLayout(pAnaLayout);
        pAnaLayout.setHorizontalGroup(
            pAnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAnaLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pAnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pAnaLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(43, 43, 43)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14))
                    .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );
        pAnaLayout.setVerticalGroup(
            pAnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAnaLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pAnaLayout.createSequentialGroup()
                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pAnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel10)
                    .addComponent(jLabel14))
                .addContainerGap())
        );

        pAtıs.setOpaque(false);

        jLabel6.setText("KALORİ");

        javax.swing.GroupLayout pAtısLayout = new javax.swing.GroupLayout(pAtıs);
        pAtıs.setLayout(pAtısLayout);
        pAtısLayout.setHorizontalGroup(
            pAtısLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAtısLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfcalori, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pAtısLayout.setVerticalGroup(
            pAtısLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAtısLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addComponent(tfcalori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout PyemekLayout = new javax.swing.GroupLayout(Pyemek);
        Pyemek.setLayout(PyemekLayout);
        PyemekLayout.setHorizontalGroup(
            PyemekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PyemekLayout.createSequentialGroup()
                .addGroup(PyemekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pAna, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PyemekLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PyemekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(PyemekLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfyisim))
                            .addGroup(PyemekLayout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                                .addComponent(tfyfiyat, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PyemekLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jcbYemek, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(pAtıs, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PyemekLayout.setVerticalGroup(
            PyemekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PyemekLayout.createSequentialGroup()
                .addGroup(PyemekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfyisim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PyemekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(tfyfiyat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(PyemekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jcbYemek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(pAna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pAtıs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        Ptatlı.setBorder(javax.swing.BorderFactory.createTitledBorder("TATLI"));
        Ptatlı.setOpaque(false);

        jLabel9.setText("İSİM");

        jLabel11.setText("FİYAT");

        jLabel12.setText("PİŞİRME ŞEKLİ");

        jcbTatlı.setBackground(new java.awt.Color(240, 197, 73));
        jcbTatlı.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FIRIN", "OCAK", "TANDIR" }));
        jcbTatlı.setSelectedIndex(-1);

        psütlü.setOpaque(false);

        jLabel18.setText("Birlikte");

        javax.swing.GroupLayout psütlüLayout = new javax.swing.GroupLayout(psütlü);
        psütlü.setLayout(psütlüLayout);
        psütlüLayout.setHorizontalGroup(
            psütlüLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(psütlüLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addGap(39, 39, 39)
                .addComponent(tfWithWhat, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        psütlüLayout.setVerticalGroup(
            psütlüLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(psütlüLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(psütlüLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(tfWithWhat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pSerbetli.setOpaque(false);

        jLabel19.setText("Şeker Türü");

        javax.swing.GroupLayout pSerbetliLayout = new javax.swing.GroupLayout(pSerbetli);
        pSerbetli.setLayout(pSerbetliLayout);
        pSerbetliLayout.setHorizontalGroup(
            pSerbetliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSerbetliLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfSugar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pSerbetliLayout.setVerticalGroup(
            pSerbetliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSerbetliLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pSerbetliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(tfSugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PtatlıLayout = new javax.swing.GroupLayout(Ptatlı);
        Ptatlı.setLayout(PtatlıLayout);
        PtatlıLayout.setHorizontalGroup(
            PtatlıLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PtatlıLayout.createSequentialGroup()
                .addGroup(PtatlıLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(psütlü, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PtatlıLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PtatlıLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PtatlıLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tftisim, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                            .addComponent(tftfiyat)
                            .addComponent(jcbTatlı, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(pSerbetli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PtatlıLayout.setVerticalGroup(
            PtatlıLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PtatlıLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PtatlıLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tftisim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(PtatlıLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tftfiyat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(28, 28, 28)
                .addGroup(PtatlıLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jcbTatlı, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(psütlü, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pSerbetli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        bEkle.setBackground(new java.awt.Color(240, 197, 73));
        bEkle.setText("ÜRÜN EKLE");
        bEkle.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        bEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEkleActionPerformed(evt);
            }
        });

        bSil.setBackground(new java.awt.Color(240, 197, 73));
        bSil.setText("ÜRÜN SİL");
        bSil.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        bSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSilActionPerformed(evt);
            }
        });

        bUrunleriGoster.setBackground(new java.awt.Color(240, 197, 73));
        bUrunleriGoster.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        bUrunleriGoster.setText("BÜTÜN ÜRÜNLERİ GÖSTER");
        bUrunleriGoster.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        bUrunleriGoster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUrunleriGosterActionPerformed(evt);
            }
        });

        pinnerYemek.setOpaque(false);

        bgyemek.add(cbAnaYemek);
        cbAnaYemek.setText("Ana Yemek");
        cbAnaYemek.setOpaque(false);
        cbAnaYemek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAnaYemekActionPerformed(evt);
            }
        });

        bgyemek.add(cbAtıstırmalıkl);
        cbAtıstırmalıkl.setText("Atıştırmalık");
        cbAtıstırmalıkl.setOpaque(false);
        cbAtıstırmalıkl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAtıstırmalıklActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pinnerYemekLayout = new javax.swing.GroupLayout(pinnerYemek);
        pinnerYemek.setLayout(pinnerYemekLayout);
        pinnerYemekLayout.setHorizontalGroup(
            pinnerYemekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pinnerYemekLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbAnaYemek)
                .addGap(18, 18, 18)
                .addComponent(cbAtıstırmalıkl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pinnerYemekLayout.setVerticalGroup(
            pinnerYemekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pinnerYemekLayout.createSequentialGroup()
                .addGroup(pinnerYemekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbAnaYemek)
                    .addComponent(cbAtıstırmalıkl))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        pinnerİcecek.setOpaque(false);

        bgyemek.add(cbSıcak);
        cbSıcak.setText("Sıcak");
        cbSıcak.setOpaque(false);
        cbSıcak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSıcakActionPerformed(evt);
            }
        });

        bgyemek.add(cbSoguk);
        cbSoguk.setText("Soğuk");
        cbSoguk.setOpaque(false);
        cbSoguk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSogukActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pinnerİcecekLayout = new javax.swing.GroupLayout(pinnerİcecek);
        pinnerİcecek.setLayout(pinnerİcecekLayout);
        pinnerİcecekLayout.setHorizontalGroup(
            pinnerİcecekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pinnerİcecekLayout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addComponent(cbSıcak)
                .addGap(28, 28, 28)
                .addComponent(cbSoguk)
                .addGap(27, 27, 27))
        );
        pinnerİcecekLayout.setVerticalGroup(
            pinnerİcecekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pinnerİcecekLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pinnerİcecekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbSıcak)
                    .addComponent(cbSoguk))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        PinnerTatlı.setOpaque(false);

        bgyemek.add(cbSutlu);
        cbSutlu.setText("Sütlü");
        cbSutlu.setOpaque(false);
        cbSutlu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSutluActionPerformed(evt);
            }
        });

        bgyemek.add(cbSerbetli);
        cbSerbetli.setText("Şerbetli");
        cbSerbetli.setOpaque(false);
        cbSerbetli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSerbetliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PinnerTatlıLayout = new javax.swing.GroupLayout(PinnerTatlı);
        PinnerTatlı.setLayout(PinnerTatlıLayout);
        PinnerTatlıLayout.setHorizontalGroup(
            PinnerTatlıLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PinnerTatlıLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(cbSutlu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(cbSerbetli)
                .addGap(26, 26, 26))
        );
        PinnerTatlıLayout.setVerticalGroup(
            PinnerTatlıLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PinnerTatlıLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PinnerTatlıLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbSutlu)
                    .addComponent(cbSerbetli))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainpanelLayout = new javax.swing.GroupLayout(mainpanel);
        mainpanel.setLayout(mainpanelLayout);
        mainpanelLayout.setHorizontalGroup(
            mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainpanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mainpanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bSil, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(121, 121, 121)
                        .addComponent(bUrunleriGoster, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mainpanelLayout.createSequentialGroup()
                        .addGroup(mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainpanelLayout.createSequentialGroup()
                                .addComponent(Pyemek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE))
                            .addGroup(mainpanelLayout.createSequentialGroup()
                                .addComponent(pinnerYemek, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(56, 56, 56)))
                        .addGroup(mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pinnerİcecek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainpanelLayout.createSequentialGroup()
                                .addComponent(Piçecek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)))
                        .addGroup(mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainpanelLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(mainpanelLayout.createSequentialGroup()
                                        .addGap(129, 129, 129)
                                        .addComponent(JRtatlı)
                                        .addGap(120, 120, 120))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainpanelLayout.createSequentialGroup()
                                        .addGap(53, 53, 53)
                                        .addComponent(PinnerTatlı, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainpanelLayout.createSequentialGroup()
                                .addComponent(Ptatlı, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainpanelLayout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(JRyemek)
                .addGap(275, 275, 275)
                .addComponent(JRiçecek)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainpanelLayout.setVerticalGroup(
            mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JRyemek)
                    .addComponent(JRiçecek)
                    .addComponent(JRtatlı))
                .addGap(8, 8, 8)
                .addGroup(mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(mainpanelLayout.createSequentialGroup()
                            .addComponent(pinnerYemek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12))
                        .addComponent(pinnerİcecek, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PinnerTatlı, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainpanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(Pyemek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainpanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Piçecek, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ptatlı, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainpanelLayout.createSequentialGroup()
                        .addComponent(bEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bSil, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bUrunleriGoster, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEkleActionPerformed
       if(cbAnaYemek.isSelected()){
           SystemClass.AddUrun(new AnaYemekler(tuzMiktarı,(String)jcbYemek.getSelectedItem(), tfyisim.getText(), Double.parseDouble(tfyfiyat.getText())));
           SystemClass.writeToAnayemek();
       }    
       else if(cbAtıstırmalıkl.isSelected()){
            SystemClass.AddUrun(new Atıştırmalıklar(tfcalori.getText(),(String)jcbYemek.getSelectedItem(), tfyisim.getText(), Double.parseDouble(tfyfiyat.getText())));    
             SystemClass.writeToAtıstırmalık();
            
       }
       else if(cbSıcak.isSelected()){
         SystemClass.AddUrun(new SıcakIcecekler(Double.parseDouble(jSpinner1.getValue().toString()),(String) jcbİçecek.getSelectedItem(),tfiisim.getText(), Double.parseDouble(tfifiyat.getText())));
         SystemClass.writeToSıcakIcecek();
       }
       else if(cbSoguk.isSelected()){
          SystemClass.AddUrun(new SogukIcecekler(buzMiktarı,(String) jcbİçecek.getSelectedItem(),tfiisim.getText(), Double.parseDouble(tfifiyat.getText())));
          SystemClass.writeSogukIcecek();
       }
       else if(cbSutlu.isSelected()){
           SystemClass.AddUrun(new SutluTatlılar(tfWithWhat.getText(),(String) jcbTatlı.getSelectedItem(), tftisim.getText(), Double.parseDouble(tftfiyat.getText())));
           SystemClass.writeToSutluTatlı();
       }
        else if(cbSerbetli.isSelected()){
            SystemClass.AddUrun(new SerbetliTatlılar(tfSugar.getText(),(String) jcbTatlı.getSelectedItem(), tftisim.getText(), Double.parseDouble(tftfiyat.getText())));
            SystemClass.writeToSerbetliTatlı();
        }
 
        setPanels();
       clear();
       
       
    }//GEN-LAST:event_bEkleActionPerformed

    private void JRyemekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRyemekActionPerformed
        pinnerYemek.setVisible(true);
        PinnerTatlı.setVisible(false);
        pinnerİcecek.setVisible(false);
        Pyemek.setVisible(false);
        Piçecek.setVisible(false);
        Ptatlı.setVisible(false);  
    }//GEN-LAST:event_JRyemekActionPerformed

    private void JRiçecekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRiçecekActionPerformed
        pinnerYemek.setVisible(false);
        pinnerİcecek.setVisible(true);
        PinnerTatlı.setVisible(false);
        Ptatlı.setVisible(false);
        Pyemek.setVisible(false);
        Piçecek.setVisible(false); 
    }//GEN-LAST:event_JRiçecekActionPerformed

    private void JRtatlıActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRtatlıActionPerformed
        pinnerYemek.setVisible(false);
        pinnerİcecek.setVisible(false);
        PinnerTatlı.setVisible(true);
        Ptatlı.setVisible(false);
        Pyemek.setVisible(false);
        Piçecek.setVisible(false);
    }//GEN-LAST:event_JRtatlıActionPerformed

    private void bUrunleriGosterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUrunleriGosterActionPerformed
         
        

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             urunjframe.tfshow.setText(SystemClass.showUruns());
                urunjframe.pSil.setVisible(false);
                urunjframe.setVisible(true);

            }
        });
        
        
    }//GEN-LAST:event_bUrunleriGosterActionPerformed

    private void bSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSilActionPerformed

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             urunjframe.tfshow.setText(SystemClass.showUruns());
             
             urunjframe.pSil.setVisible(true);
                urunjframe.setVisible(true);
                urunjframe.pSil.setVisible(true);
                
            }
        });
        
    }//GEN-LAST:event_bSilActionPerformed

    private void cbAnaYemekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAnaYemekActionPerformed

        Pyemek.setVisible(true);
        pAna.setVisible(true);
        pAtıs.setVisible(false);
        
    }//GEN-LAST:event_cbAnaYemekActionPerformed

    private void cbAtıstırmalıklActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAtıstırmalıklActionPerformed
        Pyemek.setVisible(true);
        pAna.setVisible(false);
        pAtıs.setVisible(true);
    }//GEN-LAST:event_cbAtıstırmalıklActionPerformed

    private void cbSıcakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSıcakActionPerformed
        Piçecek.setVisible(true);
        psıc.setVisible(true);
        psoguk.setVisible(false);
    }//GEN-LAST:event_cbSıcakActionPerformed

    private void cbSogukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSogukActionPerformed
        Piçecek.setVisible(true);
        psıc.setVisible(false);
        psoguk.setVisible(true);
    }//GEN-LAST:event_cbSogukActionPerformed

    private void cbSutluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSutluActionPerformed
        
        Ptatlı.setVisible(true);
        psütlü.setVisible(true);
        pSerbetli.setVisible(false);
        
    }//GEN-LAST:event_cbSutluActionPerformed

    private void cbSerbetliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSerbetliActionPerformed
        
        Ptatlı.setVisible(true);
        psütlü.setVisible(false);
        pSerbetli.setVisible(true);
    }//GEN-LAST:event_cbSerbetliActionPerformed

    private void cbazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbazActionPerformed
        jProgressBar1.setValue(33);
        buzMiktarı =0.25;
    }//GEN-LAST:event_cbazActionPerformed

    private void cbOrtaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbOrtaActionPerformed
        
        jProgressBar1.setValue(66);
        buzMiktarı=0.5;
    }//GEN-LAST:event_cbOrtaActionPerformed

    private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox6ActionPerformed
       
        jProgressBar1.setValue(99);
        buzMiktarı=0.75;
    }//GEN-LAST:event_jCheckBox6ActionPerformed

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        
        if(jSlider1.getValue()==1)
            tuzMiktarı="Az";
        else if(jSlider1.getValue()==2)
            tuzMiktarı="Orta";
        else if(jSlider1.getValue()==3)
            tuzMiktarı="Cok";
    }//GEN-LAST:event_jSlider1StateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton JRiçecek;
    private javax.swing.JRadioButton JRtatlı;
    private javax.swing.JRadioButton JRyemek;
    private javax.swing.JPanel PinnerTatlı;
    private javax.swing.JPanel Piçecek;
    private javax.swing.JPanel Ptatlı;
    private javax.swing.JPanel Pyemek;
    private javax.swing.JButton bEkle;
    private javax.swing.JButton bSil;
    private javax.swing.JButton bUrunleriGoster;
    private javax.swing.ButtonGroup bgazcokorta;
    private javax.swing.ButtonGroup bgicecek;
    private javax.swing.ButtonGroup bgtatlı;
    private javax.swing.ButtonGroup bgyemek;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cbAnaYemek;
    private javax.swing.JCheckBox cbAtıstırmalıkl;
    private javax.swing.JCheckBox cbOrta;
    private javax.swing.JCheckBox cbSerbetli;
    private javax.swing.JCheckBox cbSoguk;
    private javax.swing.JCheckBox cbSutlu;
    private javax.swing.JCheckBox cbSıcak;
    private javax.swing.JCheckBox cbaz;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JComboBox<String> jcbTatlı;
    private javax.swing.JComboBox<String> jcbYemek;
    private javax.swing.JComboBox<String> jcbİçecek;
    private javax.swing.JPanel mainpanel;
    private javax.swing.JPanel pAna;
    private javax.swing.JPanel pAtıs;
    private javax.swing.JPanel pSerbetli;
    private javax.swing.JPanel pinnerYemek;
    private javax.swing.JPanel pinnerİcecek;
    private javax.swing.JPanel psoguk;
    private javax.swing.JPanel psütlü;
    private javax.swing.JPanel psıc;
    private javax.swing.JTextField tfSugar;
    private javax.swing.JTextField tfWithWhat;
    private javax.swing.JTextField tfcalori;
    private javax.swing.JTextField tfifiyat;
    private javax.swing.JTextField tfiisim;
    private javax.swing.JTextField tftfiyat;
    private javax.swing.JTextField tftisim;
    private javax.swing.JTextField tfyfiyat;
    private javax.swing.JTextField tfyisim;
    // End of variables declaration//GEN-END:variables
}
